### ISSUE TITLE
Sitemap.xml generation?

### ISSUE THREAD

**Issue by commadelimited** [SimonSapin/Frozen-Flask#55]
I've raised a question about autogenerating a sitemap.xml file over on the FlatPages repo. I wondered if that perhaps should belong here instead:
https://github.com/SimonSapin/Flask-FlatPages/issues/49

**Comment by SimonSapin** [comment]
That sounds orthogonal to what Frozen-Flask (or FlatPages) does. It's not provided "out of the box", but there's also nothing stopping you from using whatever tools you would otherwise use to do it.

The whole point of Frozen-Flask (as opposed to something like Jekyll) is to give you flexibility to write Python code that does exactly what you need.
